<a href="https://colab.research.google.com/github/Lochipi/AnimalDetection/blob/main/DataAnalytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
print("Hello World, this is a practice test for Data Analytics with Numpy and Pandas")

Hello World, this is a practice test for Data Analytics with Numpy and Pandas


Numpy Library

In [64]:
import numpy as np

Creating a list in numpy

In [65]:
roll_no = [1,2,3,4]
print(roll_no)

[1, 2, 3, 4]


In [66]:
arrl = np.array([1,2,3,4])

In [67]:
print(arrl)

[1 2 3 4]


check the data type of the data.

In [68]:
type(roll_no)

list

In [69]:
type(arrl)

numpy.ndarray

Multiply, you will get list repeated

In [70]:
roll_no * 3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

Multiplication for array you will get an each multiplied 

In [71]:
arrl * 3

array([ 3,  6,  9, 12])

In [72]:
arrl + 10

array([11, 12, 13, 14])

Dimensions of the array

In [73]:
arrl.ndim

1

4 Items in it, with one dimension

In [74]:
arrl.shape

(4,)

second array, 2dim array

In [75]:
arr2 = np.array([[1,2], [3,4]])
arr2

array([[1, 2],
       [3, 4]])

In [76]:
arr2.ndim

2

In [77]:
arr2.shape

(2, 2)

Arrange Function

In [78]:
arr2 = np.arange(1,21)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [79]:
arr3 = np.arange(20, 38, 2)
arr3

array([20, 22, 24, 26, 28, 30, 32, 34, 36])

Indexing 

In [80]:
arr3[4]

28

Value at last position

you can access the last element using the last number if you know the count. This is not the best case if you have large datasets 

In [81]:
# if you know the values
arr3[8]

36

Accessing the last index using the best way, down below.

In [82]:
# nagative indexing
arr3[-1]

36

If you try to access the 9th element you can an error. ☹ 

In [83]:
arr3[9]

IndexError: ignored

In [84]:
m1 = np.arange(20, 38, 2)
m1

array([20, 22, 24, 26, 28, 30, 32, 34, 36])

In [85]:
# getting the 1st/ or 0th element 
m1[0]

20

In [86]:
m1[7]

34

In [87]:
# negative indexing
m1[-2]

34

In [ ]:
m1

In [88]:
#slicing 
# m1[start_idex : end_indx]  it doesn't inclued the last element.

m1[1:4]

array([22, 24, 26])

In [89]:
m1[ 4 : 8 ]

array([28, 30, 32, 34])

With the negative indexing, the last item starts at -1 coming to the left

In [90]:
m1[ -5 : -1 ]

array([28, 30, 32, 34])

In [91]:
# Fancy Indexing

We're checking if the elements inside m1 are less than 30, it returns true if it below else false.

In [92]:
mask = m1 < 30
mask

array([ True,  True,  True,  True,  True, False, False, False, False])

`m1[mask]` is a way to access certain elements of a NumPy array `m1`. The `mask` is a boolean array of the same shape as `m1`, used to index or filter out certain elements of `m1`

`m1[mask]` will return a new NumPy array of elements from `m1` where the corresponding element in `mask` is `True`

In [93]:
m1[mask]

array([20, 22, 24, 26, 28])

In [97]:
type(m1)

numpy.ndarray

the same can be done this way

In [95]:
m1[ m1 < 30 ]

array([20, 22, 24, 26, 28])

Down below, `m1` is an array variable. `m1%2==0` checks if the elements of the list m1 are even or not. If the element is even (leaves no remainder when divided by 2), then the condition becomes `True`. Otherwise, the condition becomes `False`.

Using square brackets [ ], we apply this condition as a filter on the list m1. It only keeps the numbers that fulfill the condition (i.e., the even numbers), and returns a new list containing only the `even numbers` from the original list m1.

In [98]:
m1[ m1%2 == 0 ]

array([20, 22, 24, 26, 28, 30, 32, 34, 36])

This code creates two one-dimensional numpy arrays- `a` and `b`, with values `[1,3,5]` and `[2,1,1]` respectively. These arrays can be used to perform mathematical operations like addition, subtraction, multiplication, etc. on them.

In [99]:
a = np.array([1,3,5])
b = np.array([2,1,1])

print(a)
print(b)

[1 3 5]
[2 1 1]


Adding the two arrays

In [100]:
a + b

array([3, 4, 6])

finding the smallest value in `a`

In [101]:
np.min(a)

1

Maximum value in `b`

In [102]:
np.max(b)

2

The average of `a`

In [103]:
np.average(a)

3.0